version: 0.2

# env:
  # variables:
    # key: "value"
    # key: "value"
            
phases:
  # install:
    # commands:
      # - command
      # - command
  # pre_build:
    # commands:
      # - command
      # - command
  build:
    commands:
      - echo build: before docker run
      - docker run -it -v $(PWD):/app --workdir /app 689765778194.dkr.ecr.us-west-2.amazonaws.com/aspnetcore-build:latest bash -c "dotnet restore && dotnet publish -c Release -o ./bin/Release/PublishOutput"
      - echo build: after docker run
  # post_build:
    # commands:
      # - command
      # - command
artifacts:
  files:
    - ./bin/Release/PublishOutput/*
    # - location
  discard-paths: yes
  # base-directory: location
