version: 0.2

# env:
  # variables:
    # key: "value"
    # key: "value"
            
phases:
  # install:
    # commands:
      # - apt-get update -y
      # - apt-get install -y docker
      # - command
  pre_build:
    commands:
      # - command
      - $(aws ecr get-login --region us-west-2)
      - ls
  build:
    commands:
      - echo Building before docker run
      - docker run -i -v $PWD:/app --workdir /app 689765778194.dkr.ecr.us-west-2.amazonaws.com/aspnetcore-build:latest bash -c "dotnet restore && dotnet publish -c Release -o ./bin/Release/PublishOutput"
      - echo Building after docker run
  # post_build:
    # commands:
      # - command
      # - command
artifacts:
  files:
    - ./bin/Release/PublishOutput/*
    # - location
  discard-paths: yes
  # base-directory: location
