version: 0.2

# env:
  # variables:
    # key: "value"
    # key: "value"
            
phases:
  install:
    commands:
      - sudo apt-get update && apt-get upgrade
      # - command
  # pre_build:
    # commands:
      # - command
      # - command
  build:
    commands:
      - echo Building before docker run
      - docker run -it -v $PWD:/app --workdir /app 689765778194.dkr.ecr.us-west-2.amazonaws.com/aspnetcore-build:latest bash -c "dotnet restore && dotnet publish -c Release -o ./bin/Release/PublishOutput"
      - echo Building after docker run
  # post_build:
    # commands:
      # - command
      # - command
artifacts:
  files:
    - ./bin/Release/PublishOutput/*
    # - location
  discard-paths: yes
  # base-directory: location
